@startuml

package "Repository" {
    [証明書] as Cert
}

package "Administrator-Register" {
    :システム管理者: as Admin
    [セキュリティキー] as Authenticator
    (登録アプリ) as GeboSigRegister

    Admin -> GeboSigRegister
    GeboSigRegister -down-> Authenticator : 初期PIN
    GeboSigRegister -down-> Cert
}

package "User-Register" {
    :ユーザーA: as User0
    [セキュリティキー] as Authenticator1
    (PIN更新アプリ) as GeboSigChangePIN
    (指紋登録アプリ) as BioPassTool

    Authenticator -down-> User0 : 初期設定された\nセキュリティキーを渡す
    User0 -left-> Authenticator1
    Authenticator1 -down-> GeboSigChangePIN
    GeboSigChangePIN -> BioPassTool
}

package "Signature" {
    [セキュリティキー] as Authenticator2
    :ユーザーA: as User
    (署名アプリ) as GeboSigSignature
    [書類ファイル] as Document
    '[電子署名] as Sig
    [署名された書類ファイル] as Zip

    User0 .down.> User
    BioPassTool -down-> Authenticator2
    Authenticator2 .right. User
    User -down-> Document
    'User -> GeboSigSignature
    Document -> GeboSigSignature  
    Authenticator2 -> GeboSigSignature
    GeboSigSignature -down-> Zip
}

package "Verify" {
    [署名された書類ファイル] as Zip2 
    :マネージャ: as Manager
    [書類ファイル] as Document2
    [電子署名] as Sig2
    (検証アプリ) as GeboSigVerify

    Zip .down.> Manager : メールなどで送信
    Manager .right.> Zip2
    Zip2 -down-> Document2
    Zip2 -down-> Sig2
    Manager -right-> GeboSigVerify : 書類ファイルの真正性チェック 
    Manager <.left. GeboSigVerify : 検証OK 

    Cert -> GeboSigVerify
    Sig2 -down-> GeboSigVerify 
    Document2 -down-> GeboSigVerify

}






@enduml